# Base image
FROM node:18-alpine AS base
WORKDIR /app/client
ENV PATH /app/client/node_modules/.bin:$PATH
COPY package.json /app/client/package.json
RUN npm install --silent

# Build image
FROM base AS build
WORKDIR /app/client
COPY . /app/client
RUN npm run build

# Production image
FROM nginx:stable-alpine AS production
COPY --from=build /app/client/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
