version: '3'

services:
  db:
    profiles:
      - 'db'
      - 'server'
      - 'dev'
    restart: on-failure
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - db-data:/data/db
    networks:
      - private

  socket_server:
    profiles:
      - 'socket-server'
      - 'server'
      - 'dev'
    restart: on-failure
    build:
      context: ./socket-server
    ports:
      - '8888:8888'
    volumes:
      - ./socket-server:/app/socket-server
    env_file:
      - ./socket-server/.env
    environment:
      PORT: '8888'
    depends_on:
      - db
    networks:
      - private

  server:
    profiles:
      - 'server'
      - 'dev'
    restart: on-failure
    build:
      context: ./server
    ports:
      - '8000:8000'
    volumes:
      - ./server:/app/server
      - ./server/public:/app/public
    env_file:
      - ./server/.env
    environment:
      NODE_ENV: 'development'
      PORT: '8000'
      SOCKET_SERVER_URL: 'ws://socket_server:8888'
      DATABASE_URL: 'mongodb://db:27017/main'
    depends_on:
      - db
      - socket_server
    networks:
      - private

  client:
    profiles:
      - 'client'
      - 'dev'
    restart: on-failure
    build:
      context: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app/client
    env_file:
      - ./client/.env
    environment:
      CI: 'true'
      PORT: '3000'
      NODE_ENV: 'development'
      REACT_APP_API_URL: 'http://server:8000'
      SOCKET_SERVER_URL: 'ws://socket_server:8888'
    depends_on:
      - db
      - socket_server
      - server
    networks:
      - private

volumes:
  db-data:

networks:
  private:
    driver: bridge
