version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  server:
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - '8000:8000'
    volumes:
      - ./server:/app
    env_file:
      - ./server/.env
    environment:
      NODE_ENV: development
      PORT: 8000
      DATABASE_URL: postgres://user:password@db:5432/dbname
    depends_on:
      - db

volumes:
  db-data:
